groups:
  - name: default
    rules:
    - alert: InternalServerError
      expr: irate(hits{status="500"}) > 0
      for: 1s
      labels:
        severity: critical
      annotations:
        summary: "path {{ $labels.path }} returned status 500"
        description: "{{ $labels.path }} of job {{ $labels.job }} returned status {{ $labels.status }}"
